# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='showtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
