# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 10:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tv.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_movies_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reviews', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi']), tv.validators.file_size]),
        ),
    ]
