# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 16:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tv.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20180411_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='feedbacks', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi']), tv.validators.file_size]),
        ),
    ]
