# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_auto_20180411_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='source',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
