# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_messages_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='read',
            new_name='read_status',
        ),
    ]
